### DISCUSSION TITLE
Geobox

### DISCUSSION THREAD

**Discussion by madlazim** [nikosT/Gisola#25] [General]
@nikosT 
I tried to create points of Indonesia region as like this: 
Geobox: (12.4000,87.3800), (-12.5900,87.0000), (-12.59,158.1900), (12.3770,158.1900), (12.4000,87.3800). However, I get the Gisola produced MT solution for earthquakes occurred outside of Indonesia. I don't know how to determine the points of Geobox? Thanks

**Comment by nikosT** [comment]
Hi @madlazim,

Geobox parameter is defined in two completely different parts.

1.  Determining which crustal model to use on which particular location, e.g:
```YAML
Crustal:
    - Filepath: crustals/drakatos.vz
      Geobox: (22.6163,37.6465), (23.3432,36.8208), (24.6418,36.6669), (25.6634,37.5202), (24.9950,38.6259), (23.6373,39.4235), (22.3654,39.2644), (21.8251,39.1394), (22.6163,37.6465)
```
2. Determining which events to catch based on their hypocenter's location, e.g.:
```YAML
Watcher:
  Magnitudetype: MLh # set specific hypocenter magnitude type or null for all
  Range: 540 # check interval in sec
  Playback: 0 # set sec for past-time run
  Historical: false # use this only if Playback is not zero and you want to reproduce the exact scenario
  Geobox: (20.3054,37.2037), (22.4079,33.6323), (27.0569,33.8793), (30.3113,35.8225), (27.4245,41.5998), (24.9779,42.0729), (21.7796,41.8349), (18.6751,40.6285), (20.3054,37.2037) # null indicates not bounds
  ```

However, they have relativity, since if for example you catch an event but you do not define a crustal model (or null -which defines default case-), then Gisola will not be instructed on which crustal model to use and the MT will not be competed.

In your case, do you receive a particular error? If yes, could you reply with it?

For creating a Geobox easily you could use [https://earth.google.com](https://earth.google.com). Specifically, draw points/lines and save them to a project. Then, download/export the project in kml file and copy-paste the coordinates value to Geobox.

Thanks
