### DISCUSSION TITLE
Service for Indonesia Event

### DISCUSSION THREAD

**Discussion by madlazim** [nikosT/Gisola#8] [Usage Questions]
Hi Nikos,

Many thanks for your NEW software release Gisola. I am very happy to receive the email. I have successfully installed the Gisola by using your template and Service:
    - [FDSNWS, http://eida.gein.noa.gr, null] # get metadata from NOA
    - [FDSNWS, http://www.orfeus-eu.org, null] # get metadata from ODC
    - [StationXML, inventory.xml] # get metadata from file
However,  I want to use event occurred in Indonesia with Service:
- https://geofon.gfz-potsdam.de/eqinfo/list.php
How should I write the configuration?

Best wishes,

Madlazim

**Comment by nikosT** [comment]
Hi @madlazim,

You need to modify the respective file: [https://github.com/nikosT/Gisola/wiki/Configuration](https://github.com/nikosT/Gisola/wiki/Configuration).

According to your link, you need to change:

```yaml
# This service is used to provide Gisola with a catalog of 
# seismic events, either for real-time or past-time operation.  
# FDSNWS-event service can only be used here.
Event:
  Host: http://geofon.gfz-potsdam.de
```
And also, if you want real-time monitoring you need to alter coordinates on Geobox in your area (see example below):
```yaml
Watcher:
...
  Geobox: (20.3054,37.2037), (22.4079,33.6323), (27.0569,33.8793), (30.3113,35.8225), (27.4245,41.5998), (24.9779,42.0729), (21.7796,41.8349), (18.6751,40.6285), (20.3054,37.2037) # null indicates not bounds
...
```

Otherwise, if you need to just run specific events, you can download it from the geofon.gfz-potsdam.de FDSNWS-event the list of the events in QuakeML (e.g. [using obspy)](http://geofon.gfz-potsdam.de/fdsnws/event/1/query?limit=100&format=xml)).

See FDSNWS-event specifications (to limit to your geographical area and perhaps magnitude type and size, etc) at [https://www.fdsn.org/webservices/fdsnws-event-1.2.pdf](https://www.fdsn.org/webservices/fdsnws-event-1.2.pdf).

When you download the XML file (e.g. events.xml), you just need to feed the program with it (such as the test benchmark):
```bash
./gisola.py --event-xml events.xml
```
